pipeline {
    agent any

    // Parameters for pipeline
    parameters {
        string(name: 'BRANCH_TO_BUILD', defaultValue: 'dev', description: 'Branch to build: dev or main')
    }

    environment {
        DEV_REPO = "sipserver/devrepo"
        PROD_REPO = "sipserver/prodrepo"
        DOCKER_CREDENTIALS = "dockerhub-creds01" // Jenkins credential ID for DockerHub login
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out source code for branch: ${params.BRANCH_TO_BUILD}"
                checkout([$class: 'GitSCM',
                    branches: [[name: "${params.BRANCH_TO_BUILD}"]],
                    userRemoteConfigs: [[
                        url: 'https://github.com/sridhar20ece/devops-build.git',
                        credentialsId: 'git_PAT01'
                    ]]
                ])
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Making build.sh executable..."
                sh 'chmod +x build.sh'

                echo "Running build.sh script..."
                // Pass the branch parameter to build.sh
                sh "./build.sh ${params.BRANCH_TO_BUILD}"
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // Read the image tag generated by build.sh
                    def imageTag = readFile('image_tag.txt').trim()
                    echo "Pushing Docker image: ${imageTag}"

                    withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIALS, 
                                                      usernameVariable: 'DOCKER_USER', 
                                                      passwordVariable: 'DOCKER_PASS')]) {
                        sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                        sh "docker push ${imageTag}"
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build and push completed successfully!'
        }
        failure {
            echo 'Build or push failed.'
        }
    }
}
